package quicktest;

import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ListaLigada miLista = new ListaLigada();
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaDatos = new javax.swing.JLabel();
        botonAgregarInicio = new javax.swing.JButton();
        botonAgregarFinal = new javax.swing.JButton();
        botonEliminarInicio = new javax.swing.JButton();
        botonEliminarFinal = new javax.swing.JButton();
        textoDato = new javax.swing.JTextField();
        botonOrdenado = new javax.swing.JButton();
        botonEliminarEspecifico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        etiquetaDatos.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        etiquetaDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonAgregarInicio.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonAgregarInicio.setText("Agregar en inicio");
        botonAgregarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarInicioActionPerformed(evt);
            }
        });

        botonAgregarFinal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonAgregarFinal.setText("Agregar en final");
        botonAgregarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarFinalActionPerformed(evt);
            }
        });

        botonEliminarInicio.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonEliminarInicio.setText("Eliminar en inicio");
        botonEliminarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarInicioActionPerformed(evt);
            }
        });

        botonEliminarFinal.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonEliminarFinal.setText("Eliminar en final");
        botonEliminarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFinalActionPerformed(evt);
            }
        });

        textoDato.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        textoDato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonOrdenado.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonOrdenado.setText("Agregar ordenado");
        botonOrdenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenadoActionPerformed(evt);
            }
        });

        botonEliminarEspecifico.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        botonEliminarEspecifico.setText("Eliminar específico");
        botonEliminarEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEspecificoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(textoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(etiquetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonAgregarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAgregarInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                    .addComponent(botonOrdenado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonEliminarInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(botonEliminarEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(etiquetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(textoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarInicio)
                    .addComponent(botonEliminarInicio))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(botonEliminarFinal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonAgregarFinal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEliminarEspecifico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOrdenado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarInicioActionPerformed
        miLista.eliminarCabeza();
        etiquetaDatos.setText(miLista.imprimir());
    }//GEN-LAST:event_botonEliminarInicioActionPerformed

    private void botonAgregarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarInicioActionPerformed
        try{
            miLista.insertarCabeza(Integer.parseInt(textoDato.getText()));
            textoDato.setText("");
            etiquetaDatos.setText(miLista.imprimir());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "¡TIPO DE DATO NO VÁLIDO!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            textoDato.setText("");
        }
    }//GEN-LAST:event_botonAgregarInicioActionPerformed

    private void botonAgregarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarFinalActionPerformed
       try{
            miLista.insertarCola(Integer.parseInt(textoDato.getText()));
            textoDato.setText("");
            etiquetaDatos.setText(miLista.imprimir());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "¡TIPO DE DATO NO VÁLIDO!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            textoDato.setText("");
        }
    }//GEN-LAST:event_botonAgregarFinalActionPerformed

    private void botonEliminarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFinalActionPerformed
        miLista.eliminarCola();
        etiquetaDatos.setText(miLista.imprimir());
    }//GEN-LAST:event_botonEliminarFinalActionPerformed

    private void botonOrdenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenadoActionPerformed
        try{
            miLista.insertarOrdenado(Integer.parseInt(textoDato.getText()));
            textoDato.setText("");
            etiquetaDatos.setText(miLista.imprimir());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "¡TIPO DE DATO NO VÁLIDO!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            textoDato.setText("");
        }
    }//GEN-LAST:event_botonOrdenadoActionPerformed

    private void botonEliminarEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEspecificoActionPerformed
        try{
            miLista.eliminaSeleccionado(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el dato que desea eliminar:")));
            etiquetaDatos.setText(miLista.imprimir());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "¡TIPO DE DATO NO VÁLIDO!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonEliminarEspecificoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarFinal;
    private javax.swing.JButton botonAgregarInicio;
    private javax.swing.JButton botonEliminarEspecifico;
    private javax.swing.JButton botonEliminarFinal;
    private javax.swing.JButton botonEliminarInicio;
    private javax.swing.JButton botonOrdenado;
    private javax.swing.JLabel etiquetaDatos;
    private javax.swing.JTextField textoDato;
    // End of variables declaration//GEN-END:variables
}
